version: '3'
services:

  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog

  postgresql:
    image: 'bitnami/postgresql:12'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data_12:/bitnami/postgresql12'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=secret
      - POSTGRESQL_DATABASE=sentiment_analyzer
      - ALLOW_EMPTY_PASSWORD=yes

  1_python_posts:
    build: ./
    depends_on:
      - 2_kafka_posts
    command: python 1_python_posts.py
    restart: on-failure

  2_kafka_posts:
    image: confluentinc/cp-kafka:5.3.0
    hostname: 2_kafka_posts
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://2_kafka_posts:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_ADVERTISED_HOST_NAME: 2_kafka_posts
      KAFKA_CREATE_TOPICS: "posts:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/2_kafka_posts"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/2_kafka_posts/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  3_python_proclenguaje:
    build: ./
    depends_on:
      - 4_kafka_proclenguaje
    command: python 3_python_proclenguaje.py
    restart: on-failure

  4_kafka_proclenguaje:
    image: confluentinc/cp-kafka:5.3.0
    hostname: 4_kafka_proclenguaje
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://4_kafka_proclenguaje:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_ADVERTISED_HOST_NAME: 4_kafka_proclenguaje
      KAFKA_CREATE_TOPICS: "proclenguaje:1:1"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181/4_kafka_proclenguaje"
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - ./data/4_kafka_proclenguaje/data:/var/lib/kafka/data
    depends_on:
      - zookeeper

  5_python_analysis:
    build: ./
    command: python 5_python_analysis.py
    restart: on-failure

volumes:
  postgresql_data_12:
    driver: local